### ISSUE TITLE
You stole my code!!!

### ISSUE THREAD

**Issue by JackLSummer15** [WorteJD/JUST-DANCE-MAINSCENE-GENERATOR-FOR-WII#3]
Why did you take part of my code without my permission for the encryptors?!?

**Comment by WorteJD** [comment]
Hi there. I am sorry for doing that and I can for sure credit you or ask you. But I didn't have any contact with you and your code got deleted from GitHub, so I just did that. By the way, the code is in alpha, undone, so I used it just for this prototype, which is still not fully working. If I can ask, can I use it? I didn't have time to do one.

**Comment by WorteJD** [comment]
Encoder deleted from the code. Closing the issue.
